### ISSUE TITLE
Adding `--no-emit` option results in error

### ISSUE THREAD

**Issue by jonhue** [tj/commander.js#1237]
Adding the option `.option('--no-emit', 'description')` to a command results in the following error when running `bin cmd -h`:

```
/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:1495
    this.emit(this._helpLongFlag);
         ^

TypeError: this.emit is not a function
    at Command.outputHelp (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:1495:10)
    at outputHelpIfRequested (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:1645:9)
    at Command._parseCommand (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:893:7)
    at Command._dispatchSubcommand (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:860:18)
    at Command._parseCommand (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:877:12)
    at Command.parse (/mnt/c/code/tony-lang/cli/node_modules/commander/index.js:712:10)
    at Object.<anonymous> (/mnt/c/code/tony-lang/cli/dist/index.js:26:20)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```

Is this expected?

**Comment by shadowspawn** [comment]
The problem is due to a clash of your option name with the properties of the Command object, in this case  the `emit` method from `EventListener`. The value for the `--no-emit` flag is stored as the `emit` property and overwrites the expected method. 

To resolve the problem, you may opt-in to a new way of storing the option values using `.storeOptionsAsProperties(false)` which was added specifically to avoid this sort of problem.

See https://github.com/tj/commander.js#avoiding-option-name-clashes

**Comment by jonhue** [comment]
Thanks, that makes sense! 🙂

**Comment by shadowspawn** [comment]
Opened a PR to add a warning for option name clashes: #1275
