### ISSUE TITLE
this.name is not a function when trying to run mocha tests 

### ISSUE THREAD

**Issue by nyck33** [tj/commander.js#1324]
On p.48 of O'Reilly's Web Development with Node and Express, there is a command to run a logic test to check the return type of a function is a string.  The command is:
```
mocha -u tdd -R spec qa/tests-unit.js
```
I `sudo npm install commander -g` then it told me it cannot find module `glob` so I `npm install glob -g` then it wanted `npm install debug -g` then `npm install diff -g` so I did them all and now get:
```
nobu@my_machine:~/project_folder$ mocha -u tdd -R spec qa/tests-unit.js
/usr/lib/node_modules/commander/index.js:1228
    const partCommands = [this.name()];
                               ^

TypeError: this.name is not a function
    at Command.unknownCommand (/usr/lib/node_modules/commander/index.js:1228:32)
    at Command._parseCommand (/usr/lib/node_modules/commander/index.js:983:16)
    at Command.parse (/usr/lib/node_modules/commander/index.js:778:10)
    at Object.<anonymous> (/usr/lib/nodejs/mocha/bin/_mocha:183:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
The book does not say anything about installing commander.
My `package.json` shows:
![image](https://user-images.githubusercontent.com/25189545/89632758-96160000-d857-11ea-90b8-8bddeb588e22.png)

**Comment by shadowspawn** [comment]
My best guess from the information available is that mocha is not installed correctly. 

Commander is used as a dependency of your program or of a package your program uses. It it not normally installed globally since it does not offer any commands itself.

**Comment by nyck33** [comment]
@shadowspawn Thanks, I'll try that.
