### ISSUE TITLE
exitOverride does not work as expected

### ISSUE THREAD

**Issue by GregTheGreek** [tj/commander.js#1366]
I can't seem to override the error handling within commander.js.

A reproducible error can be used in our project, and the following instructions can show that easily:
```shell
git clone git@github.com:ChainSafe/Anemone.git
git checkout greg/rpc
yarn dev:start -- rpc exists --fakeflag // or npm run dev:start -- rpc exists --fakeflag
```

The file in question is [here](https://github.com/ChainSafe/Anemone/blob/greg/rpc/src/index.ts)

Any help would be greatly appreciated

**Comment by shadowspawn** [comment]
From a quick look at your file, you have probably hit a limitation. There are a number of behaviours including `.exitOverride()` that are only applied to subcommands which are added using `.command()`. They aren't applied to subcommands added using `.addCommand()` as they may change the runtime behaviour, and the author of that "other" code may have relied on default behaviours.

Short version is, try calling `.exitOverride()` on the subcommands too when setting them up, or when adding them in the loop.

(I'll have a longer more careful look later.)

**Comment by GregTheGreek** [comment]
@shadowspawn thanks for the quick reply! ok i will give that a go!

**Comment by GregTheGreek** [comment]
yep that did it!

**Comment by GregTheGreek** [comment]
is there a way to silence the commander error? For example im receiving the following:
```
error: unknown option '--fewf'
Usage: index [options] [command]

Anemone is an Ethereum node compatibility testing tool.

Options:
  -h, --help      display help for command

Commands:
  evm             Tests related to the Ethereum Virtual Machine (EVM)
  rpc             Tests related to the Ethereum JSON-RPC
  help [command]  display help for command
/home/greg/code/github.com/ChainSafe/Anemone/node_modules/commander/index.js:367
          throw err;
          ^

CommanderError: (outputHelp)
    at Command._exit (/home/greg/code/github.com/ChainSafe/Anemone/node_modules/commander/index.js:388:26)
    at Command.help (/home/greg/code/github.com/ChainSafe/Anemone/node_modules/commander/index.js:1680:10)
    at Object.<anonymous> (/home/greg/code/github.com/ChainSafe/Anemone/lib/index.js:28:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  name: 'CommanderError',
  code: 'commander.help',
  exitCode: 0,
  nestedError: undefined
}
```

**Comment by shadowspawn** [comment]
1) There is not a way to suppress the displayed error at the start, the `.exitOverride` just replaces the call to `process.exit` when the error occurs.

> error: unknown option '--fewf'

2) Took me a while to realise why you are also getting a stack. In the `catch` you are calling `.help()`, but that calls `.exit()` and the override makes it throw again. Tricky! You could call `.outputHelp()` instead which does not throw.

```
    try {
        program.parse(process.argv);
    } catch (e) {
        //program.help();
        program.outputHelp();
        process.exit(1)
    }
```
