### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] for Commander Arguments?

### ISSUE THREAD

**Issue by fireflysemantics** [tj/commander.js#1542]
After upgrading Node to 16.2.0 I started getting `TypeError [ERR_INVALID_ARG_TYPE]` exceptions for commands receiving arguments.

I upgraded commander to the latest version, but I'm still getting the same errors.

```
Oles-MacBook-Pro:d oleersoy$ fsd new test
Info: 2021-06-04 04:19:23 Creating a documentation project with project name fs-test-md
Info: 2021-06-04 04:19:23 Writing project files
node:internal/fs/utils:853
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type function ([Function (anonymous)])
    at Object.writeFileSync (node:fs:2137:5)
    at Command.<anonymous> (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/lib/commands/new.js:48:10)
    at Command.listener [as _actionHandler] (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/node_modules/commander/index.js:1460:12)
    at Command.parse (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/node_modules/commander/index.js:1292:10)
    at Object.<anonymous> (/Users/oleersoy/.nvm/versions/node/v16.2.0/lib/node_modules/@fireflysemantics/fsd-cli/index.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Thoughts?

**Comment by fireflysemantics** [comment]
Closing ... I think Node is catching an error that it was not catching before.
