### ISSUE TITLE
TypeError: line.trimEnd is not a function

### ISSUE THREAD

**Issue by kolserdav** [tj/commander.js#2048]
I have that error in node `v8.17.0`:
```sh
/home/kol/Projects/cli/node_modules/commander/lib/help.js:457
      return ((i > 0) ? indentString : '') + line.trimEnd();
                                                  ^

TypeError: line.trimEnd is not a function
    at lines.map (/home/kol/Projects/cli/node_modules/commander/lib/help.js:457:51)
    at Array.map (<anonymous>)
    at Help.wrap (/home/kol/Projects/cli/node_modules/commander/lib/help.js:455:31)
    at Help.formatHelp (/home/kol/Projects/cli/node_modules/commander/lib/help.js:368:38)
    at Command.helpInformation (/home/kol/Projects/cli/node_modules/commander/lib/command.js:1983:19)
    at Command.outputHelp (/home/kol/Projects/cli/node_modules/commander/lib/command.js:2023:32)
    at Command.help (/home/kol/Projects/cli/node_modules/commander/lib/command.js:2073:10)
    at Command._parseCommand (/home/kol/Projects/cli/node_modules/commander/lib/command.js:1275:12)
    at Command.parse (/home/kol/Projects/cli/node_modules/commander/lib/command.js:910:10)
    at Object.<anonymous> (/home/kol/Projects/cli/index.js:110:9)
```
Maybe you should specify explicitly the minimal engine version in `package.json` !?

**Comment by shadowspawn** [comment]
We do specify engine in `package.json`, and include our oldest support version of node in the tests. What version of Commander are you using?

https://github.com/tj/commander.js/blob/f1ae2db8e2da01d6efcbfd59cbf82202f864b0c1/package.json#L76-L78

**Comment by kolserdav** [comment]
Thanks for the quick response. Yes, I see it now. I just didn’t look at the package file, because for some reason I expected that the version below could not be installed.
```sh
npm WARN notsup Unsupported engine for commander@11.1.0: wanted: {"node":">=16"} (current: {"node":"8.17.0","npm":"6.13.4"})
```

**Comment by shadowspawn** [comment]
Commander 7 is the newest version which runs on node v8.
