### ISSUE TITLE
Git-style sub-commands; ENOENT: no such file or directory

### ISSUE THREAD

**Issue by gajus** [tj/commander.js#390]
Sub-commands using dedicated files do not work (resolve to non-existing base executable).

This should provide enough debug information:

```sh
$ node ./src/bin/mirror foobar titles
fs.js:838
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT: no such file or directory, lstat '/mirror/src/bin/mirror'
    at Error (native)
    at fs.lstatSync (fs.js:838:18)
    at exports.readlinkSync (/mirror/node_modules/commander/node_modules/graceful-readlink/index.js:5:7)
    at Command.executeSubCommand (/mirror/node_modules/commander/index.js:472:14)
    at Command.parse (/mirror/node_modules/commander/index.js:443:17)
    at Object.<anonymous> (/mirror/src/bin/mirror.js:15:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
```

As expected, `/mirror/src/bin/mirror` does not exist.

```sh
$ ls '/mirror/src/bin/mirror'
ls: /mirror/src/bin/mirror: No such file or directory
```

`/mirror/src/bin/mirror.js` does exist (though it is not resolved by commander). Even if I specify to use that file, I get error saying that sub-command does not exist.

```sh
$ ls '/mirror/src/bin/mirror.js'
/mirror/src/bin/mirror.js
$ node ./src/bin/mirror.js foobar titles

  mirror-foobar(1) does not exist, try --help

$ cat ./src/bin/mirror
cat: ./src/bin/mirror: No such file or directory
```

` ./src/bin/mirror.js`

```js
'use strict';

let commander = require('commander'),
    jsonfile = require('jsonfile'),
    version = jsonfile.readFileSync(__dirname + '/../../package.json').version;

commander
    .version(version)
    .command('foobar', 'FOO BAR.')
    .parse(process.argv);

if (!commander.args.length) {
    commander.outputHelp();
}
```

**Comment by gajus** [comment]
The following does work (when calling the sub-command itself).

```sh
node ./src/bin/mirror-foobar titles
```

**Comment by zhiyelee** [comment]
same as #372 , this will be fixed in next release, you can use the workaround suggested here: https://github.com/tj/commander.js/issues/372

**Comment by gajus** [comment]
Thank you

**Comment by zhiyelee** [comment]
@gajus Sorry for that, I'll release a new version ASAP
