### ISSUE TITLE
subcommands do not work with babel-node

### ISSUE THREAD

**Issue by gajus** [tj/commander.js#418]
```
clear; babel-node --stage 0 -- ./src/bin/mirror parser
```

Will throw:

``` sh
fs.js:97
      throw er;
      ^
Error: ENOENT: no such file or directory, lstat '/foo/src/bin/mirror'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at exports.readlinkSync (/foo/node_modules/commander/node_modules/graceful-readlink/index.js:5:7)
    at Command.executeSubCommand (/foo/node_modules/commander/index.js:499:14)
    at Command.parse (/foo/node_modules/commander/index.js:463:17)
    at Object.<anonymous> (/foo/src/bin/mirror.js:9:6)
    at Module._compile (module.js:426:26)
    at normalLoader (/Users/gajus/.nvm/versions/io.js/v2.3.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gajus/.nvm/versions/io.js/v2.3.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:351:32)
```

However,

``` sh
clear; babel-node --stage 0 -- ./src/bin/mirror-parser
```

will work fine.

I am guessing this is because of how `babel-node` compiles the code and uses `node` to run it, which would affect the path resolution.

**Comment by zhiyelee** [comment]
hi @gajus , can paste the relative code here?

**Comment by gajus** [comment]
It is as simple as:

```js
'use strict';

let commander = require('commander');

commander
    .description('foosbars')
    .command('foo', 'Foo.')
    .parse(process.argv);
```

Where the latter is the contents of `mirror.js`, which is supposed to load `mirror-foo.js`. I doubt if `mirror-foo.js` contents is relevant, but suppose it is:

```js
'use strict';

let commander = require('commander');

commander
    .command('something')
    .description('Description.')
    .action((env) => {
        // Hello
    });

commander.parse(process.argv);
```

**Comment by gajus** [comment]
I knew I have opened an issue about this before, https://github.com/tj/commander.js/issues/390.

**Comment by gajus** [comment]
That said, https://github.com/tj/commander.js/issues/372 is closed. The bug is present in 2.8.1.

**Comment by sundowndev** [comment]
Same issue here.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
