### ISSUE TITLE
Subcommand error spawn EACCES in osx

### ISSUE THREAD

**Issue by oknoorap** [tj/commander.js#634]
I've read your documentation using sub command. After I installed globally via `npm -g`. In windows it's run normal, but I got this error in osx.

```
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1008:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/deux-cli/node_modules/commander/index.js:534:14)
    at Command.parse (/usr/local/lib/node_modules/deux-cli/node_modules/commander/index.js:463:17)
```

**Comment by berwin** [comment]
I have the same problem

**Comment by chad-vanet** [comment]
Make sure your sub command file is executable (chmod)

**Comment by vanesyan** [comment]
It's error with access permission, can you, please, apply `chmod -x` on your executable.

**Comment by vincentmrlau** [comment]
`sudo chmod a+x <your sub command file>`

**Comment by shadowspawn** [comment]
Solution supplied, and issue is still findable by people having same issue.

This issue has not had much activity recently. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
