### ISSUE TITLE
 I use "yyy" command in any "xxx" file,there will be a error: con't find module "/path/to/xxx-yyy"

### ISSUE THREAD

**Issue by fengzi2016** [tj/commander.js#815]
code :
```js
   //commander.js
    program
    .option('-p, --path <string>','your local path such as ./')
    .command('push <ak> <sk> <ifcli>')
    .action(function (cmd,ak,sk,ifcli) {})
```
the commander is  "lizi"
 when I write "lizi push 111 222 yes"
then
```js
Error: Cannot find module 'E:\github\qiuniu-upload\commander-push'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by JohnRGee** [comment]
I can not reproduce with your example code, but from the error I think you are triggering [Git-style sub-commands ](https://github.com/tj/commander.js#git-style-sub-commands) by using `.command()` with a description argument like `.command("push", "push description")`. 

If that is the issue then you probably want to call `.description` instead like:
```
program
    .option('-p, --path <string>','your local path such as ./')
    .command('push <ak> <sk> <ifcli>')
    .description("push description")
    .action(function (cmd,ak,sk,ifcli) {})
```

**Comment by fengzi2016** [comment]
Thanks for the reply , the error was solved.
