### ISSUE TITLE
Argument value ignored and treated as something else

### ISSUE THREAD

**Issue by Berkmann18** [tj/commander.js#846]
I have (basically) this code:
```js
const prgm = prgm = require('commander');
const str = (val) => val;

prgm.arguments('[files...]')
  .version(pkg.version)
  .description(pkg.description)
  .option('-f, --format [format]', 'Specify the format of the output (text (default), json, csv)', str, 'text')
  .option('-o, --output [path]', 'Output to a file instead of in the STDOUT', str, 'stdout')
  .option('-i, --interactive', 'Forces to read the input from the STDIN')
  .option('-p, --prettify', 'Prettify the output')
  .action((files) => {
    console.debug('format=', prgm.format);
    console.debug('output=', prgm.output);
    console.debug('interactive=', prgm.interactive);

    validInput = true;
    let input = (prgm.interactive) ? 'stdin' : 'any';
    hmj.run(prgm.format, input, prgm.output, files, !!prgm.prettify);
  })
  .parse(process.argv);
```
I'm trying to run `npm start -f csv examples/ex0.js` where `npm start: node index.js` but it returns
```bash
format= text
output= stdout
interactive= undefined
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'csv'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at readFilesSync (/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:262:20)
    at Object.run (/home/maxie/Dropbox/Projects/HashMyJS/src/hashmyjs.js:333:46)
    at Command.prgm.arguments.version.description.option.option.option.option.action (/home/maxie/Dropbox/Projects/HashMyJS/index.js:34:9)
    at Command.listener (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:653:12)
    at Command.parse (/home/maxie/Dropbox/Projects/HashMyJS/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/maxie/Dropbox/Projects/HashMyJS/index.js:36:4)
```
When I'm **expecting** it to print the samething as `node index -f csv examples/ex0.js` which prints:
```bash
format= csv
output= stdout
interactive= undefined
examples/ex0.js,...
```
I tried using `String` instead of the `str` function (even with a `String` cast in it) but it didn't change anything.
Why is that happening?

**Comment by JohnRGee** [comment]
You need `--` to stop npm from consuming the `-f` when using `npm run`. i.e.

    npm start -- -f csv examples/ex0.js

See [npm-run-script](https://docs.npmjs.com/cli/run-script)

I saw a warning from npm confirming it is processing the `-f` when I tried reproducing your command:

    $ npm start -f csv examples/ex0.js
    npm WARN using --force I sure hope you know what you are doing.
    ....
