### ISSUE TITLE
Run commander -> TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by renanbastos93** [tj/commander.js#911]
```
/Users/renan.bastos/Desktop/git/azion-cli/node_modules/commander/index.js:176
  var args = name.split(/ +/);
                  ^

TypeError: Cannot read property 'split' of undefined
    at Command.command (/Users/renan.bastos/Desktop/git/azion-cli/node_modules/commander/index.js:176:19)
    at /Users/renan.bastos/Desktop/git/azion-cli/bin/cli.js:12:14
    at Object.<anonymous> (/Users/renan.bastos/Desktop/git/azion-cli/bin/cli.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by vanesyan** [comment]
Hello there! Can you please post code related to commander, so we find the root of problem quicker. Thanks!

**Comment by renanbastos93** [comment]
example code:

```js
(function(){
    "use strict";
    const program = require('commander');
    const asks = require("./../src/conf.json").asks;

    program
    .version('0.0.1')
    .description('testing!');
    
    for (let currentCli in asks) {
        program
            .command(currentCli.command)
            .alias(currentCli.alias)
            .description(currentCli.description)
            .action(
                function(...args) {
                    currentCli.action(...args);
                }
            );
    }
    
    program.parse(process.argv);
    return;
})();
```

**Comment by vanesyan** [comment]
Is issue resolved for you? Is it mistake in your code or maybe issue lays in commander?

**Comment by renanbastos93** [comment]
Activity hold, so I waiting to continue a task.
